---
# argument spec file for myorg.custom_collection.database
argument_specs:
  main:
    short_description: "Arguments for the database role"
    description: "This role manages PostgreSQL database users and databases within an existing PostgreSQL instance."
    author: "David Danielsson"
    options:
      database_server_name:
        type: "str"
        description: "The name of the database to create"
        default: "webapp_prod"

      database_server_user:
        type: "str"
        description: "The name of the database user to create"
        default: "webapp_user"

      database_server_password:
        type: "str"
        description: "The password for the database user"
        default: "SecurePassword123"
        no_log: true
...
