---
# argument spec file for myorg.custom_collection.database

argument_specs:
  main:
    short_description: Role description.
    options:
      my_variable:
        type: str
        description: A simple string argument for demonstration.
        default: "default_value"
