---
argument_specs:
  main:
    short_description: Role description.
    description:
      - myorg.custom_collection monitoring Role
    author:
      - foo
    options:
      my_variable:
        description: A simple string argument for demonstration.
        type: str
        required: true
...
