---
# Platform-specific variables for RedHat family
# Included automatically based on ansible_os_family

# Package names for RHEL/CentOS/Rocky
__webserver_packages:
  - httpd
  - mod_ssl
  - httpd-tools

__webserver_service: httpd
__webserver_user: apache
__webserver_group: apache
__webserver_config_path: /etc/httpd/conf/httpd.conf
__webserver_config_validate: /usr/sbin/httpd -t -f %s

...
