---
# handlers file for database
- name: Restart database
  ansible.builtin.service:
    name: "{{ database_service }}"
    state: restarted
  become: true

- name: Reload database
  ansible.builtin.service:
    name: "{{ database_service }}"
    state: reloaded
  become: true
...
